server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
cloud:
  gateway:
    routes:
      - id: /api/signup
        uri: http://localhost:8092
        predicates:
          -Path=/**

      - id: /api/login
        uri: http://localhost:8091
        predicates:
          - Path=/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env,health,metrics,info




